### PR TITLE
[Maintenance] Remove 'exceptionable' field setting, and artifacts

### PR DESCRIPTION
**Pull request by pzl**
This is part of some package cleanup effort

### CODE REVIEW

**Review by paul-tavares — APPROVED** [review]
I'm 👍 from a perspective of "sure, looks ok" 😆 
But you should really get the 👍's from folks on the Detections side and Endpoint as this would be more of an impact (I think) for them

**Review by jonathan-buttner — APPROVED** [review]
Thanks for doing this @pzl !

**Comment by ferullo** [comment]
I don't know how this PR works. As long as the same endpoint document fields are available for exceptions I'm happy.

**Comment by pzl** [comment]
Who is a good person to have review and approve this from the perspective:

>  the same endpoint document fields are available for exceptions

**Review by marshallmain — APPROVED** [review]

**Comment by ferullo** [comment]
> Who is a good person to have review and approve this from the perspective

I'm not sure. I guess @marshallmain and @jonathan-buttner approving means it must work? Functionally, a test would be to make sure that with this package in use you can still create malware alert exceptions on any field in the alert except the few we don't allow. For instance I am pretty sure `file.Ext.malware_classification.identifier` should be allowed but `file.Ext.quarantine_result` should not be, even though it is in the alert (since you Endpoint can't apply an exception after it has quarantined the file...)

**Comment by jonathan-buttner** [comment]
> Who is a good person to have review and approve this from the perspective:
> 
> > the same endpoint document fields are available for exceptions

The changes look good. Nothing changed in the `package/endpoint` directory which is what matters for determining if the mapping is being changed.

**Comment by pzl** [comment]
Off-thread, it appears Marshall was the original, intended consumer of the exceptionable files, and doesn't use them. I will take his sign-off as the deity-level-approval here

**Pull request merged**
