### PR TITLE
Transform schema v2

### PR DESCRIPTION
**Pull request by pzl**
## Change Summary

Updated the transform definitions to match the new [Transform Spec](https://github.com/elastic/package-spec/pull/307)

this involved mostly renaming files and translating from json to yaml

I tested these package changes against this PR: https://github.com/elastic/kibana/pull/140046

You can see that the new transforms are installed below.

image

I added an Endpoint to make sure the data was still making it's way to the Endpoint list.

image

## Release Target

next

### For mapping changes:

- [x] I ran `make` after making the schema changes, and committed all changes
- [x] If this is a `metadata` change, I also updated both transform destination schemas to match

### For Transform changes:

- [x] The new transform successfully starts in Kibana
- [x] The corresponding transform destination schema was updated if necessary

Upgrade (from current json-based transform) & downgrade operate successfully

### CODE REVIEW

**Comment by pzl** [comment]
It appears that Fleet may not yet support installing packages following the new spec.

Here is the fleet issue tracker for that support: https://github.com/elastic/kibana/issues/134321

**Comment by kevinlog** [comment]
@joeypoon @pzl 

I resolved the conflicts in this file by updating `go.mod` and `go.sum` in addition to adding the new mappings to the `united` index.

Let me know if it looks OK to you.  I tested installing the package with this change with this PR: https://github.com/elastic/kibana/pull/140046. We can merge if everything goes in on the Fleet side.

**Comment by pzl** [comment]
@kevinlog looks good, verified the two extra fields (`last_checkin_message`, `components`)  from Joey's united change are in here. The resulting diff looks correct. I can't self-approve my PR, but all looks good here. 

will keep holding until kibana PR gets merged

**Comment by kevinlog** [comment]
@pzl 

looks good!  Can you just confirm that you stood this up and it installed correctly in a locally running stack?

**Comment by pzl** [comment]
@kevinlog 

Yes, This worked correctly in a local stack. Tested three scenarios:

- fresh install (no bundled endpoint package in kibana, installed this fresh). :heavy_check_mark: 
- upgrade (started with package from `main` branch, installed, checked that transforms for main (json-style-v1) were running. Then restarted my local EPR to include the new build and kibana upgraded endpoint package (played with manifest version locally to make sure it picked it up) and checked that old transforms were stopped, removed, and the new yml-style-v2 were the ones now running :heavy_check_mark: 
- downgrade put some intentional errors in the package so it downgraded to previous json ones :heavy_check_mark:

**Review by kevinlog — APPROVED** [review]
LGTM!

**Pull request merged**
