### PR TITLE
[memory_protection_event] memory_region.mapped_path

### PR DESCRIPTION
**Pull request by jdu2600**
## Change Summary

`mapped_path` was not initially included in the memory_protection_event subset for `memory_region`. However, this field is required in some scenarios. 

It is currently referenced in the descriptions of other included fields such as `mapped_pe_detected` which is defined as "Whether the file at mapped_path is an executable".

## Release Target
 * 8.1

### For mapping changes:
- [X] I ran `make` after making the schema changes, and committed any generated files (in `schema/`, `generated/`)
- [x] Does this field need to be "exceptionable"? (no longer specified in this package, this is now tracked in Kibana)
- [ ] If this is a `metadata` change, I also updated both transform destination schemas to match

### For Transform changes:
- [ ] The new transform successfully starts in Kibana
- [ ] The corresponding transform destination schema was updated if necessary

### CODE REVIEW

**Comment by jdu2600** [comment]
Hi @jonathan-buttner 
Are you able to take a look at this change please?

Endpoint's ECS validation tests pass with this update.

**Review by jonathan-buttner — APPROVED** [review]
Looks good to me!

**Review by pzl — APPROVED** [review]
looks good, thanks for including `example` with this :+1:

**Comment by jdu2600** [comment]
Thanks both!

**Pull request merged**
