### PR TITLE
[Terminal output] Fields coming in 8.5 added to custom_schemas/subsets

### PR DESCRIPTION
**Pull request by mitodrummer**
## Change Summary

A few fields and mappings have been added in order to support the new Terminal Output feature coming out in 8.5

The ECS changes are currently merged to main, but since it won't go out till 8.5, I've added a subset of the changes here in endpoint-package.

### Sample values
```
{
  process: {
    tty: {
      rows: 24,
      columns: 80
    },
    io: {
      type: 'tty',
      text: "helloworld",
      total_bytes_captured: 1024,
      total_bytes_skipped: 0,
      bytes_skipped: [],
      max_bytes_per_process_exceeded: false
    }
}
```
## Release Target

8.5

### For mapping changes:

- [x] I ran `make` after making the schema changes, and committed all changes

### CODE REVIEW

**Comment by mitodrummer** [comment]
Had this problem in my last PR, but for some reason i'm not getting all the generate artifacts, and so haven't been able to validate these changes work... hopefully CI will give some insights.

**Comment by mitodrummer** [comment]
Yup, so for some reason, make or make -B is not producing the expected generated schemas.. I'm using ubuntu 22 with python3.10

**Review by pzl — COMMENTED** [review]
We seem to be losing some top-level definitions of the `tty` object here. the sub-fields under it (eg `X.tty.Y` seem to still be here, just the docs and description of the `tty` object, which is strange.

Not sure if that's intentional or we have some out-of-date ECS building happening

**Comment by mitodrummer** [comment]
> We seem to be losing some top-level definitions of the `tty` object here. the sub-fields under it (eg `X.tty.Y` seem to still be here, just the docs and description of the `tty` object, which is strange.
> 
> Not sure if that's intentional or we have some out-of-date ECS building happening

Yea that is strange, I wonder if the custom_schemas changes are some how overriding everything else under the tty object. I can try and include the rest of the fields for the tty object to see if that fixes it. Though, my local build issues are a blocker at the moment. Thanks to @joeypoon for the help in getting the right artifacts committed.

**Comment by mitodrummer** [comment]
Building works great on OSX (dusted off my old MBP 2015).

**Review by pzl — APPROVED** [review]

**Pull request merged**
