### PR TITLE
Keylogging (Win32k ETW) API Event metrics

### PR DESCRIPTION
**Pull request by AsuNa-jp**
## Change Summary

Adds new metrics fields for the keylogging events (ETW Win32k API Event provider).

```
Endpoint.metrics.system_impact.win32k_events.week_idle_ms
Endpoint.metrics.system_impact.win32k_events.week_ms
```

## Release Target

These events are diagnostic in 8.10 and will be released in a future version.

### For mapping changes:

- [x] I ran `make` after making the schema changes, and committed all changes
- [ ] If these field(s) are "exception"-able, I made a companion PR to Kibana adding it (see [Readme](https://github.com/elastic/endpoint-package#exceptionable))
- [ ] If this is a `metadata` change, I also updated both transform destination schemas to match

### CODE REVIEW

**Review by matthewscherer — APPROVED** [review]

**Review by patrykkopycinski — APPROVED** [review]

**Comment by AsuNa-jp** [comment]
Hi @parkiino  @patrykkopycinski! I think this PR is ready to be merged, but please let me know if I need any modifications or something.

**Comment by pzl** [comment]
@AsuNa-jp can you please add example values for these new fields to [`package/endpoint/data_stream/metrics/sample_event.json`](https://github.com/elastic/endpoint-package/blob/main/package/endpoint/data_stream/metrics/sample_event.json)?

It is run as part of automated testing, equivalent to adding tests for the mapping changes. The document is indexed and verifies that any fields in the `sample_event.json` has a mapping entry, and that the types match.

**Comment by AsuNa-jp** [comment]
@pzl 
>It is run as part of automated testing, equivalent to adding tests for the mapping changes.
Thanks for letting me know about above.

I added the nessesary fields and values in the `sample_event.json`. Furthermore, I also found missing fields and values (the following), so I added these to the `sample_event.json` too.

* `Endpoint.metrics.system_impact.cred_access_events.week_ms`
* `Endpoint.metrics.system_impact.threat_intelligence_events.week_ms`

I think it is now ready to be merged, but if I need any additional fixes, please feel free to let me know.

**Review by pzl — APPROVED** [review]
looks great, thanks for adding that. you're good to merge whenever you're ready

**Pull request merged**
