### PR TITLE
Consolidate fork,exec,exit for macOS

### PR DESCRIPTION
**Pull request by nicholasberlin**
## Change Summary

Changes are for aggregation of fork, exec, and exit process events for macOS.

## Release Target

8.16

### For mapping changes:

- [x] I ran `make` after making the schema changes, and committed all changes
- [ ] If these field(s) are "exception"-able, I made a companion PR to Kibana adding it (see [Readme](https://github.com/elastic/endpoint-package#exceptionable))
- [ ] If this is a `metadata` change, I also updated both transform destination schemas to match

Chained off of: https://github.com/elastic/endpoint-package/pull/543

### CODE REVIEW

**Review by gabriellandau — COMMENTED** [review]
Will documents sent from old endpoints comply with this latest schema?

**Comment by nicholasberlin** [comment]
> Will documents sent from old endpoints comply with this latest schema?

I believe so. Can someone help me test that?

**Comment by ferullo** [comment]
> I believe so. Can someone help me test that? @elastic/security-defend-workflows perhaps?

If non aggregated events pass EAF when this custom documentation verification is in effect for current Endpoints I think it's inherently backwards compatible, right? Either way, EAF can do this testing. I think @intxgo can help with how to do that though I can too if needed.

**Comment by nicholasberlin** [comment]
Test PR against 8.15 with this branch as endpoint-package: https://github.com/elastic/endpoint-dev/pull/14911
Buildkite run: https://buildkite.com/elastic/endpoint-dev/builds/8743

**Comment by intxgo** [comment]
@ferullo custom documentation validation is ON by default in EAF, however what @nicholasberlin is asking for seems the schema validation, which also in ON by default, the only point here @nicholasberlin is to point EAF branch to this commit branch, run combine schema, push and run EAF.

**Review by gabriellandau — APPROVED** [review]

**Pull request merged**
