### PR TITLE
4420 update doc generator

### PR DESCRIPTION
**Pull request by jrmolin**
## Change Summary

I added some new documentation in a new directory structure: `custom_documentation`, which parallels the `package/` directory.

This adds new filtering fields-per-event, which is used to output new os/event/field documentation, as requested by a customer in https://github.com/elastic/sdh-endpoint/issues/163, and tracked in issue https://github.com/elastic/security-team/issues/4420.

This does not affect the current output documentation, but does create some new files that should be made accessible to customers through some website. Also, the format has not been decided on by anyone.

## Release Target

8.7, I think.

### CODE REVIEW

**Comment by tomsonpl** [comment]
Hey @jrmolin, thanks for doing the changes :) I was assigned for the review, but I do not know this codebase well enough to safely review 38k lines of code :P Do you think somebody more experiences with endpoint-package could take over?

**Comment by jrmolin** [comment]
So @tomsonpl, the PR looks a lot more intimidating than it is. The majority of the lines of changes are actually generated documentation updates or new doc files. The code itself exists in `scripts/generate-docs` and is pretty standard go. This is actually my first experience with the language, so it might be incorrect in places. I mostly copied what I saw elsewhere.

**Comment by ferullo** [comment]
I converted this back to a draft PR. I'm going to push several updates of the next few days/weeks. I'll re open it and reach out for reviews when my changes are in.

**Comment by ferullo** [comment]
I'm closing this in favor of this PR chain https://github.com/elastic/endpoint-package/pull/389 https://github.com/elastic/endpoint-package/pull/390 https://github.com/elastic/endpoint-package/pull/391 https://github.com/elastic/endpoint-package/pull/392

**Pull request closed without merging**
