### PR TITLE
set malware_signature.primary.matches as unindexed keyword

### PR DESCRIPTION
**Pull request by pzl**
## Change Summary

Changes from `nested` to `keyword`. Looks like the expected values are an array of concrete values (strings, it looks like)

this stems from https://github.com/elastic/endpoint-package/issues/211

### Sample values

Sample document:

```json
        "malware_signature": {
          "all_names": "Linux.EICAR.Not-a-virus",
          "identifier": "production-malware-signature-v1-linux",
          "primary": {
            "matches": [
              "WDVPIVAlQEFQWzRcUFpYNTQoUF4pN0NDKTd9JEVJQ0FSLVNUQU5EQVJELUFOVElWSVJVUy1URVNULUZJTEUhJEgrSCo="
            ],
        },


```

## Release Target

7.16

### For mapping changes:

- [x] I ran `make` after making the schema changes, and committed any generated files (in `schema/`, `generated/`)
- [ ] ~~Does this field need to be "exceptionable"? (no longer specified in this package, this is now tracked in Kibana)~~
- [ ] ~~If this is a `metadata` change, I also updated both transform destination schemas to match~~

### CODE REVIEW

**Comment by gogochan** [comment]
Is there a way not to index it, but just keeping it within the store? This is just a binary blob, which I don't think we need to search.
https://github.com/elastic/endpoint-package/pull/155#issuecomment-872418477

**Comment by pzl** [comment]
If we don't need to search it _or_ make exceptions on it, then we can just remove the mapping? or make it `enabled: false` I believe.

If a field is just incidentally retrieved with the rest of a document, we don't need to map it at all.

If we need to search, filter, sort, alert, or alert-exception on a field, we generally need to map it. Do we know what the intent behind adding this field's mapping was? IIRC it was part of a large group of additions in #200

**Review by joeypoon — APPROVED** [review]

**Comment by ferullo** [comment]
@joe-desimone @dstepanic17 @threat-punter do you have thoughts on Dan's question about exceptions?

**Comment by joe-desimone** [comment]
I have always thought of matches as informational, so I think not searchable or exceptionable would be fine. Unless Dan S/Seth have a specific use case I am not thinking of.

**Comment by dstepanic17** [comment]
I can't think any of use cases that come to mind. There should be other fields that are better for exceptionlisting and they also don't need to be searchable.

**Review by gogochan — APPROVED** [review]

**Review by kevinlog — APPROVED** [review]

**Pull request merged**
