### PR TITLE
Add `Target.process.Ext.authentication_id` and `process.Ext.authentication_id` to Security events

### PR DESCRIPTION
**Pull request by ayfaouzi**
Add `Target.process.Ext.authentication_id` and `process.Ext.authentication_id` to Security events

### Sample values

```json
{
    "@timestamp": "2024-07-02T09:54:58.3992113Z",
    "Target": {
        "process": {
            "Ext": {
                "authentication_id": "0x3e7"
            }
        }
    },
    "agent": {
        "id": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
        "type": "endpoint",
        "version": "8.15.0-SNAPSHOT"
    },
    "data_stream": {
        "dataset": "endpoint.events.security",
        "namespace": "default",
        "type": "logs"
    },
    "ecs": {
        "version": "8.10.0"
    },
    "elastic": {
        "agent": {
            "id": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"
        }
    },
    "event": {
        "action": "log_on",
        "category": [
            "authentication",
            "session"
        ],
        "code": "4624",
        "created": "2024-07-02T09:54:58.3992113Z",
        "dataset": "endpoint.events.security",
        "id": "NcDCKv79HHIfb3Vx++++++jJ",
        "kind": "event",
        "module": "endpoint",
        "outcome": "success",
        "sequence": 1751,
        "type": [
            "start"
        ]
    },
    "host": {
        "architecture": "x86_64",
        "hostname": "desktop-id050rc",
        "id": "dabadaba-0000-0000-0000-000000000000",
        "ip": [
            "10.224.0.7",
            "127.0.0.1",
            "::1"
        ],
        "mac": [
            "42-01-0a-e0-00-07"
        ],
        "name": "desktop-id050rc",
        "os": {
            "Ext": {
                "variant": "Windows 10 Pro"
            },
            "family": "windows",
            "full": "Windows 10 Pro 22H2 (10.0.19045.4529)",
            "kernel": "22H2 (10.0.19045.4529)",
            "name": "Windows",
            "platform": "windows",
            "type": "windows",
            "version": "22H2 (10.0.19045.4529)"
        }
    },
    "message": "Endpoint security event",
    "process": {
        "Ext": {
            "authentication_id": "0x3e7",
            "code_signature": [
                {
                    "exists": true,
                    "status": "trusted",
                    "subject_name": "Microsoft Windows Publisher",
                    "trusted": true
                }
            ],
            "session_info": {
                "logon_type": "Service"
            }
        },
        "code_signature": {
            "exists": true,
            "status": "trusted",
            "subject_name": "Microsoft Windows Publisher",
            "trusted": true
        },
        "entity_id": "YWFhYWFhYWEtYWFhYS1hYWFhLWFhYWEtYWFhYWFhYWFhYWFhLTcwOC0xNzE5ODk3OTkxLjc0NTY0NjAw",
        "executable": "C:\\Windows\\System32\\services.exe",
        "name": "C:\\Windows\\System32\\services.exe"
    },
    "user": {
        "domain": "WORKGROUP",
        "effective": {
            "domain": "NT AUTHORITY",
            "id": "S-1-5-18",
            "name": "SYSTEM"
        },
        "id": "S-1-5-18",
        "name": "DESKTOP-ID050RC$"
    },
    "winlog": {
        "event_data": {
            "PrivilegeList": []
        }
    }
}
```

### For mapping changes:

- [x] I ran `make` after making the schema changes, and committed all changes
- [ ] If these field(s) are "exception"-able, I made a companion PR to Kibana adding it (see [Readme](https://github.com/elastic/endpoint-package#exceptionable))
- [ ] If this is a `metadata` change, I also updated both transform destination schemas to match

### For Transform changes:

- [ ] The new transform successfully starts in Kibana
- [ ] The corresponding transform destination schema was updated if necessary

### CODE REVIEW

**Review by pzl — APPROVED** [review]
This looks good. PR failures are normal + expected in this time period after stack FF but before 8.16.0-SNAPSHOT images get generated. The failure is not on your end, I would expect passing CI as soon as the images are up

**Review by intxgo — APPROVED** [review]

**Comment by pzl** [comment]
@ayfaouzi this PR had to be reverted.

It looks like the fields were not added properly.

Fields for data streams need to be added under `custom_subsets/elastic_endpoint/<data stream>/*.yaml` and then `make`, they should not be added to `package/endpoint` directly.

**Comment by ayfaouzi** [comment]
Thanks @pzl, I just created a new PR with the suggested instruction.

It worked fine for the 2 keys I tried to add previsouly in the PR, but a third key I wanted to add as well caused an issue:
```json
  winlog:
    fields:
      event_data:
        fields:
          PrivilegeList: {}
```

Seems like he is not familir with `winlog`. 

image

**Comment by ayfaouzi** [comment]
>  If winlog.event_data.PrivilegeList is an ECS field, please let me know (though, due to the capital letters used, I assume it is not ECS. convention is to use lowercase fields unless explicitly defining a custom non-ECS field).

Yes, this field was on purpose made in such casing because we're trying to match `winlogbeat`'s format. I just asked my team for weather the fields inside `winlog.event_data.` will be ECS fields. I will get back to you soon.

**Comment by jdu2600** [comment]
`winlogbeat` fields (including non-standard CamelCase) are documented here -
https://www.elastic.co/guide/en/beats/winlogbeat/current/exported-fields-winlog.html

I don't think that this makes them "in ECS" though?

Is there a mechanism of importing definitions from the winlogbeat schema into endpoint-package?  Or do we need to duplicate the definitions?
cc: @marc-gr

**Comment by pzl** [comment]
we don't have a mechanism to import definitions from winlogbeat, no. The definitions would be duplicated here under `custom_schemas`.

re: casing: if its being done to match a field elsewhere, that's a pretty satisfactory answer to me

**Pull request merged**
